In [32]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import keras
from keras import Sequential
from keras.layers import Dense
from keras.utils import normalize

In [33]:
data = pd.read_csv('ml-practice/50_Startups.csv')

In [34]:
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [35]:
# We need to predict profit.
data.drop(columns=['State'], axis=1, inplace=True)

In [36]:
data.head()

R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

In [37]:
labels = data.Profit.values
features = data.drop(columns=['Profit']).values

In [7]:
len(features)

50

In [8]:
len(labels)

50

In [9]:
# Building model
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, random_state=3, shuffle=True, test_size=0.5)

In [15]:
model = Sequential()
model.add(Dense(3, input_dim=features_train.shape[1]))
model.add(Dense(1, activation="linear"))

In [22]:
model.compile(optimizer="adam", loss=keras.losses.mse, metrics=['mean_squared_error'])

In [23]:
from sklearn.metrics import r2_score

In [28]:
model.fit(features_train, labels_train, epochs=100, validation_data=(features_test, labels_test))

Train on 25 samples, validate on 25 samples
Epoch 1/100
25/25 [==============================] - 0s 253us/step - loss: nan - mean_squared_error: nan - val_loss: nan - val_mean_squared_error: nan
Epoch 2/100
25/25 [==============================] - 0s 214us/step - loss: nan - mean_squared_error: nan - val_loss: nan - val_mean_squared_error: nan
Epoch 3/100
25/25 [==============================] - 0s 152us/step - loss: nan - mean_squared_error: nan - val_loss: nan - val_mean_squared_error: nan
Epoch 4/100
25/25 [==============================] - 0s 125us/step - loss: nan - mean_squared_error: nan - val_loss: nan - val_mean_squared_error: nan
Epoch 5/100
25/25 [==============================] - 0s 157us/step - loss: nan - mean_squared_error: nan - val_loss: nan - val_mean_squared_error: nan
Epoch 6/100
25/25 [==============================] - 0s 159us/step - loss: nan - mean_squared_error: nan - val_loss: nan - val_mean_squared_error: nan
Epoch 7/100
25/25 [==============================]

Epoch 55/100
25/25 [==============================] - 0s 129us/step - loss: nan - mean_squared_error: nan - val_loss: nan - val_mean_squared_error: nan
Epoch 56/100
25/25 [==============================] - 0s 121us/step - loss: nan - mean_squared_error: nan - val_loss: nan - val_mean_squared_error: nan
Epoch 57/100
25/25 [==============================] - 0s 132us/step - loss: nan - mean_squared_error: nan - val_loss: nan - val_mean_squared_error: nan
Epoch 58/100
25/25 [==============================] - 0s 124us/step - loss: nan - mean_squared_error: nan - val_loss: nan - val_mean_squared_error: nan
Epoch 59/100
25/25 [==============================] - 0s 120us/step - loss: nan - mean_squared_error: nan - val_loss: nan - val_mean_squared_error: nan
Epoch 60/100
25/25 [==============================] - 0s 165us/step - loss: nan - mean_squared_error: nan - val_loss: nan - val_mean_squared_error: nan
Epoch 61/100
25/25 [==============================] - 0s 155us/step - loss: nan - mean_s

In [29]:
data.isna().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
Profit             0
dtype: int64

In [26]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
features_train = scaler.fit_transform(features_train)

In [27]:
features_test = scaler.fit_transform(features_test)

In [30]:
features_test

array([[ 0.6231827 ,  0.25616072,  0.45117972],
       [-0.67718468, -1.25132761, -0.25183395],
       [ 1.31612421, -0.37763473,  0.96915986],
       [-1.58379369,  0.5317806 , -1.89569645],
       [-0.14632132,  1.11912533, -1.06701519],
       [-0.03075383,  2.13719996, -0.78586689],
       [ 0.57918225,  0.53409768,  0.47772106],
       [-1.57104871, -2.31344204, -1.89569645],
       [-1.56027573,  0.14847213, -1.87781181],
       [ 1.58135944,  0.93202331, -0.6959837 ],
       [-0.90983551,  0.24717902, -0.00640411],
       [ 0.0040685 , -0.4771906 ,  0.96716007],
       [-0.54759666, -2.32908224, -0.04489319],
       [ 0.57346329, -0.19075133,  0.87464161],
       [ 1.75751267, -0.96540106,  1.54392036],
       [-0.06336127,  0.67207151, -0.59973939],
       [ 0.25049369,  0.06158624,  0.5874482 ],
       [ 1.10894876,  0.09624179,  0.5633084 ],
       [-0.12614519, -0.14092512, -1.03965172],
       [ 0.7832611 , -0.95184062,  0.45028837],
       [ 1.47984799,  0.87528428,  1.146

In [38]:
features

array([[ 165349.2 ,  136897.8 ,  471784.1 ],
       [ 162597.7 ,  151377.59,  443898.53],
       [ 153441.51,  101145.55,  407934.54],
       [ 144372.41,  118671.85,  383199.62],
       [ 142107.34,   91391.77,  366168.42],
       [ 131876.9 ,   99814.71,  362861.36],
       [ 134615.46,  147198.87,  127716.82],
       [ 130298.13,  145530.06,  323876.68],
       [ 120542.52,  148718.95,  311613.29],
       [ 123334.88,  108679.17,  304981.62],
       [ 101913.08,  110594.11,  229160.95],
       [ 100671.96,   91790.61,  249744.55],
       [  93863.75,  127320.38,  249839.44],
       [  91992.39,  135495.07,  252664.93],
       [ 119943.24,  156547.42,  256512.92],
       [ 114523.61,  122616.84,  261776.23],
       [  78013.11,  121597.55,  264346.06],
       [  94657.16,  145077.58,  282574.31],
       [  91749.16,  114175.79,  294919.57],
       [  86419.7 ,  153514.11,       0.  ],
       [  76253.86,  113867.3 ,  298664.47],
       [  78389.47,  153773.43,  299737.29],
       [  

In [39]:
labels

array([ 192261.83,  191792.06,  191050.39,  182901.99,  166187.94,
        156991.12,  156122.51,  155752.6 ,  152211.77,  149759.96,
        146121.95,  144259.4 ,  141585.52,  134307.35,  132602.65,
        129917.04,  126992.93,  125370.37,  124266.9 ,  122776.86,
        118474.03,  111313.02,  110352.25,  108733.99,  108552.04,
        107404.34,  105733.54,  105008.31,  103282.38,  101004.64,
         99937.59,   97483.56,   97427.84,   96778.92,   96712.8 ,
         96479.51,   90708.19,   89949.14,   81229.06,   81005.76,
         78239.91,   77798.83,   71498.49,   69758.98,   65200.33,
         64926.08,   49490.75,   42559.73,   35673.41,   14681.4 ])

In [40]:
features = normalize(features)

In [41]:
features

array([[ 0.31900633,  0.26411537,  0.91020769],
       [ 0.32756301,  0.30495941,  0.89426072],
       [ 0.34294681,  0.22606362,  0.91174707],
       [ 0.33862972,  0.2783483 ,  0.89880595],
       [ 0.35238805,  0.22662705,  0.90799936],
       [ 0.33070362,  0.25030226,  0.9099362 ],
       [ 0.56834481,  0.62147181,  0.53921884],
       [ 0.34450073,  0.38477307,  0.85631123],
       [ 0.32960386,  0.40664771,  0.85205571],
       [ 0.35598308,  0.31368211,  0.88027245],
       [ 0.37180672,  0.40347749,  0.83604167],
       [ 0.35387225,  0.3226534 ,  0.87787768],
       [ 0.3174251 ,  0.43056755,  0.84489816],
       [ 0.30552127,  0.45000055,  0.83914019],
       [ 0.37069634,  0.48382514,  0.79277832],
       [ 0.36832626,  0.39435538,  0.84191425],
       [ 0.2589657 ,  0.40364491,  0.87750074],
       [ 0.28558943,  0.43771251,  0.85255289],
       [ 0.27862765,  0.34673377,  0.89562398],
       [ 0.49055449,  0.87141052,  0.        ],
       [ 0.23205365,  0.34651784,  0.908

In [42]:
features

array([[ 0.31900633,  0.26411537,  0.91020769],
       [ 0.32756301,  0.30495941,  0.89426072],
       [ 0.34294681,  0.22606362,  0.91174707],
       [ 0.33862972,  0.2783483 ,  0.89880595],
       [ 0.35238805,  0.22662705,  0.90799936],
       [ 0.33070362,  0.25030226,  0.9099362 ],
       [ 0.56834481,  0.62147181,  0.53921884],
       [ 0.34450073,  0.38477307,  0.85631123],
       [ 0.32960386,  0.40664771,  0.85205571],
       [ 0.35598308,  0.31368211,  0.88027245],
       [ 0.37180672,  0.40347749,  0.83604167],
       [ 0.35387225,  0.3226534 ,  0.87787768],
       [ 0.3174251 ,  0.43056755,  0.84489816],
       [ 0.30552127,  0.45000055,  0.83914019],
       [ 0.37069634,  0.48382514,  0.79277832],
       [ 0.36832626,  0.39435538,  0.84191425],
       [ 0.2589657 ,  0.40364491,  0.87750074],
       [ 0.28558943,  0.43771251,  0.85255289],
       [ 0.27862765,  0.34673377,  0.89562398],
       [ 0.49055449,  0.87141052,  0.        ],
       [ 0.23205365,  0.34651784,  0.908

In [43]:
labels = normalize(labels)

In [44]:
labels

array([[ 0.22866507,  0.22810635,  0.22722426,  0.21753302,  0.1976543 ,
         0.18671613,  0.18568306,  0.18524311,  0.18103185,  0.17811581,
         0.17378897,  0.17157377,  0.16839361,  0.15973737,  0.1577099 ,
         0.15451579,  0.15103803,  0.14910825,  0.14779584,  0.14602368,
         0.14090614,  0.13238925,  0.13124657,  0.1293219 ,  0.1291055 ,
         0.12774049,  0.12575334,  0.12489079,  0.12283807,  0.12012906,
         0.11885997,  0.11594129,  0.11587502,  0.11510324,  0.1150246 ,
         0.11474713,  0.10788306,  0.10698029,  0.09660913,  0.09634355,
         0.09305401,  0.09252942,  0.08503616,  0.08296729,  0.07754549,
         0.07721931,  0.05886143,  0.05061807,  0.04242789,  0.01746121]])

In [45]:
features

array([[ 0.31900633,  0.26411537,  0.91020769],
       [ 0.32756301,  0.30495941,  0.89426072],
       [ 0.34294681,  0.22606362,  0.91174707],
       [ 0.33862972,  0.2783483 ,  0.89880595],
       [ 0.35238805,  0.22662705,  0.90799936],
       [ 0.33070362,  0.25030226,  0.9099362 ],
       [ 0.56834481,  0.62147181,  0.53921884],
       [ 0.34450073,  0.38477307,  0.85631123],
       [ 0.32960386,  0.40664771,  0.85205571],
       [ 0.35598308,  0.31368211,  0.88027245],
       [ 0.37180672,  0.40347749,  0.83604167],
       [ 0.35387225,  0.3226534 ,  0.87787768],
       [ 0.3174251 ,  0.43056755,  0.84489816],
       [ 0.30552127,  0.45000055,  0.83914019],
       [ 0.37069634,  0.48382514,  0.79277832],
       [ 0.36832626,  0.39435538,  0.84191425],
       [ 0.2589657 ,  0.40364491,  0.87750074],
       [ 0.28558943,  0.43771251,  0.85255289],
       [ 0.27862765,  0.34673377,  0.89562398],
       [ 0.49055449,  0.87141052,  0.        ],
       [ 0.23205365,  0.34651784,  0.908

In [46]:
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, random_state=3)

ValueError: Found input variables with inconsistent numbers of samples: [50, 1]

In [47]:
features

array([[ 0.31900633,  0.26411537,  0.91020769],
       [ 0.32756301,  0.30495941,  0.89426072],
       [ 0.34294681,  0.22606362,  0.91174707],
       [ 0.33862972,  0.2783483 ,  0.89880595],
       [ 0.35238805,  0.22662705,  0.90799936],
       [ 0.33070362,  0.25030226,  0.9099362 ],
       [ 0.56834481,  0.62147181,  0.53921884],
       [ 0.34450073,  0.38477307,  0.85631123],
       [ 0.32960386,  0.40664771,  0.85205571],
       [ 0.35598308,  0.31368211,  0.88027245],
       [ 0.37180672,  0.40347749,  0.83604167],
       [ 0.35387225,  0.3226534 ,  0.87787768],
       [ 0.3174251 ,  0.43056755,  0.84489816],
       [ 0.30552127,  0.45000055,  0.83914019],
       [ 0.37069634,  0.48382514,  0.79277832],
       [ 0.36832626,  0.39435538,  0.84191425],
       [ 0.2589657 ,  0.40364491,  0.87750074],
       [ 0.28558943,  0.43771251,  0.85255289],
       [ 0.27862765,  0.34673377,  0.89562398],
       [ 0.49055449,  0.87141052,  0.        ],
       [ 0.23205365,  0.34651784,  0.908

In [48]:
labels

array([[ 0.22866507,  0.22810635,  0.22722426,  0.21753302,  0.1976543 ,
         0.18671613,  0.18568306,  0.18524311,  0.18103185,  0.17811581,
         0.17378897,  0.17157377,  0.16839361,  0.15973737,  0.1577099 ,
         0.15451579,  0.15103803,  0.14910825,  0.14779584,  0.14602368,
         0.14090614,  0.13238925,  0.13124657,  0.1293219 ,  0.1291055 ,
         0.12774049,  0.12575334,  0.12489079,  0.12283807,  0.12012906,
         0.11885997,  0.11594129,  0.11587502,  0.11510324,  0.1150246 ,
         0.11474713,  0.10788306,  0.10698029,  0.09660913,  0.09634355,
         0.09305401,  0.09252942,  0.08503616,  0.08296729,  0.07754549,
         0.07721931,  0.05886143,  0.05061807,  0.04242789,  0.01746121]])

In [51]:
model = Sequential()
model.add(Dense(1, kernel_initializer="normal", activation="linear", input_dim=features.shape[1]))

In [52]:
model.compile(optimizer="rmsprop", loss="mse")

In [53]:
model.fit(features, labels)

ValueError: Error when checking target: expected dense_7 to have shape (1,) but got array with shape (50,)

In [54]:
labels.shape

(1, 50)

In [55]:
features.shape

(50, 3)