## <u>Tfidf (Term frequency inverse docment frequency)</u>
<p>
    <ul>
        <li> Way to score the importance of words (terms) in a document based on how frequently they appear.<br>
            <li> It word appears again and again then it an important word<br>
                <li> low score if not repeated.<br>
                    <li> Formula: tf(w) * idf(w) (number of times word w appears in a doc) , idf(w) get tge log(number_of_words).
                        
                    </ul>
                    </p>

In [98]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import numpy as np

In [21]:
vect = TfidfVectorizer(stop_words="english")

In [22]:
messages = ["hi how are you", "i am fine", "what are you doing", "it is okay"]
vect.fit(messages)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words='english', strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [23]:
content = vect.transform(messages).toarray()

In [24]:
print (content)


[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


In [25]:
print (content.shape)

(4, 4)


In [26]:
df = pd.DataFrame(content, columns=vect.get_feature_names())

In [27]:
df.head()

doing  fine   hi  okay
0    0.0   0.0  1.0   0.0
1    0.0   1.0  0.0   0.0
2    1.0   0.0  0.0   0.0
3    0.0   0.0  0.0   1.0

In [30]:
import string

In [78]:
test = "hello hi..! I am fine..."

In [96]:
# Main function starts below

In [61]:
p_list = []
for i in string.punctuation:
    p_list.append(i)

In [82]:
new = ""
p = []
for word in test.split():
    for j in word:
        if j in p_list:
            p.append(j)

In [93]:
for pi in set(p):
    test = test.replace(pi,"")

In [94]:
test

'hello hi I am fine'

In [95]:
p

['.', '.', '!', '.', '.', '.']