In [17]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer, load_digits
from sklearn.datasets import california_housing
import pandas as pd
import keras
from keras import Sequential
from keras.layers import Dense

In [2]:
data = load_breast_cancer()

In [12]:
digits = load_digits()

In [13]:
len(digits.data)

1797

In [14]:
len(digits.data[0])

64

In [15]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
digits.data

array([[  0.,   0.,   5., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,  10.,   0.,   0.],
       [  0.,   0.,   0., ...,  16.,   9.,   0.],
       ..., 
       [  0.,   0.,   1., ...,   6.,   0.,   0.],
       [  0.,   0.,   2., ...,  12.,   0.,   0.],
       [  0.,   0.,  10., ...,  12.,   1.,   0.]])

In [24]:
df = pd.DataFrame(data = digits.data)

In [25]:
df

0    1     2     3     4     5     6    7    8     9  ...     54   55  \
0     0.0  0.0   5.0  13.0   9.0   1.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1     0.0  0.0   0.0  12.0  13.0   5.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
2     0.0  0.0   0.0   4.0  15.0  12.0   0.0  0.0  0.0   0.0 ...    5.0  0.0   
3     0.0  0.0   7.0  15.0  13.0   1.0   0.0  0.0  0.0   8.0 ...    9.0  0.0   
4     0.0  0.0   0.0   1.0  11.0   0.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
5     0.0  0.0  12.0  10.0   0.0   0.0   0.0  0.0  0.0   0.0 ...    4.0  0.0   
6     0.0  0.0   0.0  12.0  13.0   0.0   0.0  0.0  0.0   0.0 ...    8.0  0.0   
7     0.0  0.0   7.0   8.0  13.0  16.0  15.0  1.0  0.0   0.0 ...    0.0  0.0   
8     0.0  0.0   9.0  14.0   8.0   1.0   0.0  0.0  0.0   0.0 ...    8.0  0.0   
9     0.0  0.0  11.0  12.0   0.0   0.0   0.0  0.0  0.0   2.0 ...    4.0  0.0   
10    0.0  0.0   1.0   9.0  15.0  11.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
11    0.0  0.0   0.0   0.0  14.0  13.0   1.0  0.0  0.0   0.0 ...    0.0  0.0   
12    0.0  0.0   5.0  12.0   1.0   0.0   0.0  0.0  0.0   0.0 ...    8.0  2.0   
13    0.0  2.0   9.0  15.0  14.0   9.0   3.0  0.0  0.0   4.0 ...    6.0  0.0   
14    0.0  0.0   0.0   8.0  15.0   1.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
15    0.0  5.0  12.0  13.0  16.0  16.0   2.0  0.0  0.0  11.0 ...    0.0  0.0   
16    0.0  0.0   0.0   8.0  15.0   1.0   0.0  0.0  0.0   0.0 ...   16.0  2.0   
17    0.0  0.0   1.0   8.0  15.0  10.0   0.0  0.0  0.0   3.0 ...    0.0  0.0   
18    0.0  0.0  10.0   7.0  13.0   9.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
19    0.0  0.0   6.0  14.0   4.0   0.0   0.0  0.0  0.0   0.0 ...   16.0  2.0   
20    0.0  0.0   3.0  13.0  11.0   7.0   0.0  0.0  0.0   0.0 ...    1.0  0.0   
21    0.0  0.0   0.0   2.0  16.0  16.0   2.0  0.0  0.0   0.0 ...    2.0  0.0   
22    0.0  0.0   8.0  16.0   5.0   0.0   0.0  0.0  0.0   1.0 ...    3.0  0.0   
23    0.0  1.0   8.0  12.0  15.0  14.0   4.0  0.0  0.0   3.0 ...    0.0  0.0   
24    0.0  0.0   0.0   0.0  12.0   2.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
25    0.0  0.0  12.0   8.0   8.0   7.0   0.0  0.0  0.0   3.0 ...    0.0  0.0   
26    0.0  0.0   1.0  13.0  14.0   3.0   0.0  0.0  0.0   0.0 ...   12.0  0.0   
27    0.0  0.0   0.0   8.0  14.0  14.0   2.0  0.0  0.0   0.0 ...    0.0  0.0   
28    0.0  0.0  10.0  11.0   4.0   0.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
29    0.0  0.0   9.0  13.0   7.0   0.0   0.0  0.0  0.0   0.0 ...   16.0  2.0   
...   ...  ...   ...   ...   ...   ...   ...  ...  ...   ... ...    ...  ...   
1767  0.0  0.0   0.0   2.0  16.0   1.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1768  0.0  0.0   5.0  16.0  10.0   0.0   0.0  0.0  0.0   0.0 ...    5.0  0.0   
1769  0.0  0.0   9.0  12.0  14.0   6.0   0.0  0.0  0.0   0.0 ...    2.0  0.0   
1770  0.0  2.0  10.0  12.0  16.0   8.0   0.0  0.0  0.0   4.0 ...    5.0  0.0   
1771  0.0  0.0   0.0   6.0  12.0   6.0   0.0  0.0  0.0   0.0 ...   12.0  0.0   
1772  0.0  0.0   5.0  14.0  11.0   8.0   0.0  0.0  0.0   4.0 ...    0.0  0.0   
1773  0.0  0.0   2.0  13.0  10.0   0.0   0.0  0.0  0.0   0.0 ...   12.0  0.0   
1774  0.0  0.0   6.0  12.0  12.0   6.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1775  0.0  0.0   6.0  16.0  16.0   3.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1776  0.0  0.0  12.0  16.0  16.0   7.0   0.0  0.0  0.0   3.0 ...    7.0  0.0   
1777  0.0  0.0   0.0   2.0  14.0   0.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1778  0.0  0.0   0.0   1.0  13.0   8.0   0.0  0.0  0.0   0.0 ...    0.0  0.0   
1779  0.0  0.0   3.0  10.0  16.0  16.0   4.0  0.0  0.0   0.0 ...    0.0  0.0   
1780  0.0  3.0  14.0  15.0   6.0   0.0   0.0  0.0  0.0   7.0 ...    6.0  0.0   
1781  0.0  0.0  10.0  16.0  14.0   5.0   0.0  0.0  0.0   2.0 ...    1.0  0.0   
1782  0.0  1.0  10.0  13.0   2.0   0.0   0.0  0.0  0.0  10.0 ...   13.0  0.0   
1783  0.0  0.0  15.0  13.0   1.0   0.0   0.0  0.0  0.0   0.0 ...   14.0  0.0   
1784  0.0  0.0   1.0  10.0  14.0  13.0   1.0  0.0  0.0   0.0 ...    2.0  0.0   
1785  0

In [34]:
model = Sequential()
model.add(Dense(100, activation="relu", input_dim = digits.data.shape[1]))
model.add(keras.layers.Dropout(0.2))

model.add(Dense(75, activation="relu"))
model.add(keras.layers.Dropout(0.2))

model.add(Dense(25, activation="relu"))
model.add(keras.layers.Dropout(0.2))
model.add(Dense(10, activation="softmax"))
model.compile(optimizer="adam", loss=keras.losses.categorical_crossentropy, metrics=['acc'])

In [28]:
features = digits.data
labels = digits.target

In [29]:
features

array([[  0.,   0.,   5., ...,   0.,   0.,   0.],
       [  0.,   0.,   0., ...,  10.,   0.,   0.],
       [  0.,   0.,   0., ...,  16.,   9.,   0.],
       ..., 
       [  0.,   0.,   1., ...,   6.,   0.,   0.],
       [  0.,   0.,   2., ...,  12.,   0.,   0.],
       [  0.,   0.,  10., ...,  12.,   1.,   0.]])

In [30]:
from keras.utils import to_categorical
labels = to_categorical(labels)

In [37]:
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, random_state=2, shuffle=True)

In [35]:
model.fit(features_train, labels_train, epochs=100)

Epoch 1/100
1347/1347 [==============================] - 0s 345us/step - loss: 2.7936 - acc: 0.1789
Epoch 2/100
1347/1347 [==============================] - 0s 88us/step - loss: 1.6526 - acc: 0.4053
Epoch 3/100
1347/1347 [==============================] - 0s 88us/step - loss: 1.2828 - acc: 0.5256
Epoch 4/100
1347/1347 [==============================] - 0s 88us/step - loss: 1.0381 - acc: 0.6414
Epoch 5/100
1347/1347 [==============================] - 0s 90us/step - loss: 0.8312 - acc: 0.7127
Epoch 6/100
1347/1347 [==============================] - 0s 89us/step - loss: 0.6995 - acc: 0.7587
Epoch 7/100
1347/1347 [==============================] - 0s 98us/step - loss: 0.5914 - acc: 0.8070
Epoch 8/100
1347/1347 [==============================] - 0s 94us/step - loss: 0.4917 - acc: 0.8344
Epoch 9/100
1347/1347 [==============================] - 0s 91us/step - loss: 0.4827 - acc: 0.8434
Epoch 10/100
1347/1347 [==============================] - 0s 100us/step - loss: 0.4060 - acc: 0.8693
Epoch 1

1347/1347 [==============================] - 0s 94us/step - loss: 0.0212 - acc: 0.9933
Epoch 83/100
1347/1347 [==============================] - 0s 101us/step - loss: 0.0322 - acc: 0.9911
Epoch 84/100
1347/1347 [==============================] - 0s 92us/step - loss: 0.0282 - acc: 0.9903
Epoch 85/100
1347/1347 [==============================] - 0s 105us/step - loss: 0.0229 - acc: 0.9933
Epoch 86/100
1347/1347 [==============================] - 0s 96us/step - loss: 0.0279 - acc: 0.9918
Epoch 87/100
1347/1347 [==============================] - 0s 95us/step - loss: 0.0260 - acc: 0.9911
Epoch 88/100
1347/1347 [==============================] - 0s 89us/step - loss: 0.0320 - acc: 0.9874
Epoch 89/100
1347/1347 [==============================] - 0s 96us/step - loss: 0.0813 - acc: 0.9718
Epoch 90/100
1347/1347 [==============================] - 0s 111us/step - loss: 0.0494 - acc: 0.9889
Epoch 91/100
1347/1347 [==============================] - 0s 92us/step - loss: 0.0340 - acc: 0.9911
Epoch 92/1

In [42]:
model

In [44]:
pred = model.predict(features_test)

In [45]:
import numpy as np
pred = np.argmax(pred, axis=1)

In [48]:
pred

array([4, 0, 9, 1, 8, 7, 1, 5, 1, 6, 6, 7, 6, 1, 5, 5, 8, 6, 2, 7, 4, 6, 4,
       1, 5, 2, 9, 5, 4, 6, 5, 6, 3, 4, 0, 9, 9, 8, 4, 6, 8, 1, 5, 7, 9, 6,
       9, 6, 1, 3, 0, 1, 9, 7, 3, 3, 1, 1, 8, 8, 9, 8, 5, 8, 7, 7, 2, 5, 8,
       4, 3, 1, 3, 8, 7, 3, 3, 0, 8, 7, 2, 8, 5, 3, 8, 7, 6, 4, 6, 2, 2, 0,
       1, 1, 5, 3, 5, 7, 1, 8, 2, 2, 6, 4, 6, 7, 3, 7, 3, 9, 4, 7, 0, 3, 5,
       1, 5, 0, 3, 9, 2, 7, 3, 2, 0, 8, 1, 9, 2, 1, 5, 1, 0, 3, 4, 3, 0, 8,
       3, 2, 2, 7, 3, 1, 6, 7, 2, 8, 3, 1, 1, 6, 4, 8, 2, 1, 8, 4, 1, 3, 1,
       1, 9, 5, 4, 1, 7, 4, 8, 9, 5, 7, 6, 9, 0, 0, 4, 0, 0, 9, 0, 6, 5, 8,
       8, 3, 7, 9, 2, 0, 3, 2, 7, 3, 0, 2, 1, 5, 2, 7, 0, 6, 9, 3, 1, 1, 3,
       5, 2, 5, 5, 2, 1, 2, 9, 4, 6, 5, 5, 5, 9, 7, 1, 5, 9, 6, 3, 7, 1, 7,
       5, 1, 7, 2, 7, 5, 5, 4, 8, 6, 6, 2, 8, 7, 3, 7, 8, 0, 9, 5, 7, 4, 3,
       4, 1, 0, 3, 3, 5, 4, 1, 3, 1, 2, 5, 1, 4, 0, 3, 1, 5, 5, 7, 4, 0, 1,
       0, 8, 5, 5, 5, 4, 0, 1, 8, 6, 2, 1, 1, 1, 7, 9, 6, 7, 9, 7, 0, 4, 9,
       6, 9,

In [49]:
labels_tst

NameError: name 'labels_tst' is not defined

In [50]:
from sklearn.metrics import accuracy_score


In [52]:
features_test

array([[  0.,   0.,   0., ...,   0.,   0.,   0.],
       [  0.,   0.,   1., ...,  15.,   1.,   0.],
       [  0.,   0.,   8., ...,  13.,   2.,   0.],
       ..., 
       [  0.,   0.,   6., ...,   9.,   0.,   0.],
       [  0.,   0.,   6., ...,  14.,  13.,   0.],
       [  0.,   0.,   4., ...,   0.,   0.,   0.]])

In [53]:
labels_test = np.argmax(labels_test, axis=1)

In [54]:
labels_test

array([4, 0, 9, 1, 4, 7, 1, 5, 1, 6, 6, 7, 6, 1, 5, 5, 4, 6, 2, 7, 4, 6, 4,
       1, 5, 2, 9, 5, 4, 6, 5, 6, 3, 4, 0, 9, 9, 8, 4, 6, 8, 8, 5, 7, 9, 6,
       9, 6, 1, 3, 0, 1, 9, 7, 3, 3, 1, 1, 8, 8, 9, 8, 5, 4, 4, 7, 3, 5, 8,
       4, 3, 1, 3, 8, 7, 3, 3, 0, 8, 7, 2, 8, 5, 3, 8, 7, 6, 4, 6, 2, 2, 0,
       1, 1, 5, 3, 5, 7, 6, 8, 2, 2, 6, 4, 6, 7, 3, 7, 3, 9, 4, 7, 0, 3, 5,
       8, 5, 0, 3, 9, 2, 7, 3, 2, 0, 8, 1, 9, 2, 1, 9, 1, 0, 3, 4, 3, 0, 9,
       3, 2, 2, 7, 3, 1, 6, 7, 2, 8, 3, 1, 1, 6, 4, 8, 2, 1, 8, 4, 1, 3, 1,
       1, 9, 5, 4, 8, 7, 4, 8, 9, 5, 7, 6, 9, 0, 0, 4, 0, 0, 4, 0, 6, 5, 8,
       8, 3, 7, 9, 2, 0, 3, 2, 7, 3, 0, 2, 1, 5, 2, 7, 0, 6, 9, 3, 1, 1, 3,
       5, 2, 3, 5, 2, 1, 2, 9, 4, 6, 5, 5, 5, 9, 7, 1, 5, 9, 6, 3, 7, 1, 7,
       5, 1, 7, 2, 7, 5, 5, 4, 8, 6, 6, 2, 8, 7, 3, 7, 8, 0, 9, 5, 7, 4, 3,
       4, 1, 0, 3, 3, 5, 4, 1, 3, 1, 2, 5, 1, 4, 0, 3, 1, 5, 5, 7, 4, 0, 1,
       0, 8, 5, 5, 5, 4, 0, 1, 8, 6, 2, 1, 1, 1, 7, 9, 6, 7, 9, 7, 0, 4, 9,
       6, 9,

In [55]:
accuracy_score(labels_test, pred)

0.96888888888888891

In [56]:
from keras.models import Model
from keras.layers import Input

In [60]:
a = Input(shape = (features.shape[1],), name="input")

In [62]:
b = Dense(32)(a)

In [63]:
b

<tf.Tensor 'dense_10/BiasAdd:0' shape=(?, 32) dtype=float32>

In [64]:
a

<tf.Tensor 'input:0' shape=(?, 64) dtype=float32>

In [65]:
model = Model(inputs=a, outputs=b)

In [66]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (InputLayer)           (None, 64)                0         
_________________________________________________________________
dense_10 (Dense)             (None, 32)                2080      
Total params: 2,080
Trainable params: 2,080
Non-trainable params: 0
_________________________________________________________________


In [67]:
features, labels = load_breast_cancer(return_X_y=True)

In [68]:
features_train, features_test, labels_train, labels_test = train_test_split(features, labels)

In [82]:
inputLayer = Input(shape=(features.shape[1],), name="input")
hiddenLayer = Dense(100, activation="relu")(inputLayer)
hiddenLayer2 = Dense(100, activation="relu")(hiddenLayer)
hiddenLayer3 = Dense(65, activation="relu")(hiddenLayer2)
outputLayer = Dense(1, activation="sigmoid")(hiddenLayer3)
model = Model(inputs=[inputLayer], outputs=outputLayer)

In [83]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (InputLayer)           (None, 30)                0         
_________________________________________________________________
dense_23 (Dense)             (None, 100)               3100      
_________________________________________________________________
dense_24 (Dense)             (None, 100)               10100     
_________________________________________________________________
dense_25 (Dense)             (None, 65)                6565      
_________________________________________________________________
dense_26 (Dense)             (None, 1)                 66        
Total params: 19,831
Trainable params: 19,831
Non-trainable params: 0
_________________________________________________________________


In [86]:
model.compile(optimizer=keras.optimizers.RMSprop(), loss=keras.losses.binary_crossentropy, metrics=['acc'])

In [87]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0,

In [88]:
features[0].shape

(30,)

In [89]:
features.shape

(569, 30)

In [90]:
model.fit(features_train, labels_train, epochs=100)

Epoch 1/100
426/426 [==============================] - 0s 748us/step - loss: 6.1000 - acc: 0.6174
Epoch 2/100
426/426 [==============================] - 0s 80us/step - loss: 6.1000 - acc: 0.6174
Epoch 3/100
426/426 [==============================] - 0s 99us/step - loss: 6.1000 - acc: 0.6174
Epoch 4/100
426/426 [==============================] - 0s 82us/step - loss: 6.1000 - acc: 0.6174
Epoch 5/100
426/426 [==============================] - 0s 86us/step - loss: 6.1000 - acc: 0.6174
Epoch 6/100
426/426 [==============================] - 0s 95us/step - loss: 6.1000 - acc: 0.6174
Epoch 7/100
426/426 [==============================] - 0s 83us/step - loss: 6.1000 - acc: 0.6174
Epoch 8/100
426/426 [==============================] - 0s 94us/step - loss: 6.1000 - acc: 0.6174
Epoch 9/100
426/426 [==============================] - 0s 94us/step - loss: 6.1000 - acc: 0.6174
Epoch 10/100
426/426 [==============================] - 0s 96us/step - loss: 6.1000 - acc: 0.6174
Epoch 11/100
426/426 [======

426/426 [==============================] - 0s 85us/step - loss: 6.1000 - acc: 0.6174
Epoch 85/100
426/426 [==============================] - 0s 85us/step - loss: 6.1000 - acc: 0.6174
Epoch 86/100
426/426 [==============================] - 0s 87us/step - loss: 6.1000 - acc: 0.6174
Epoch 87/100
426/426 [==============================] - 0s 112us/step - loss: 6.1000 - acc: 0.6174
Epoch 88/100
426/426 [==============================] - 0s 92us/step - loss: 6.1000 - acc: 0.6174
Epoch 89/100
426/426 [==============================] - 0s 91us/step - loss: 6.1000 - acc: 0.6174
Epoch 90/100
426/426 [==============================] - 0s 82us/step - loss: 6.1000 - acc: 0.6174
Epoch 91/100
426/426 [==============================] - 0s 90us/step - loss: 6.1000 - acc: 0.6174
Epoch 92/100
426/426 [==============================] - 0s 95us/step - loss: 6.1000 - acc: 0.6174
Epoch 93/100
426/426 [==============================] - 0s 94us/step - loss: 6.1000 - acc: 0.6174
Epoch 94/100
426/426 [==========

In [92]:
model.predict(features_test)

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
      