In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import keras
from keras import Sequential
from keras.layers import Dense
from sklearn.datasets import load_iris

In [4]:
data = load_iris()

In [5]:
features = data.data
labels = data.target

In [6]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
features[0]

array([ 5.1,  3.5,  1.4,  0.2])

In [8]:
len(features)

150

In [9]:
model = Sequential()
model.add(Dense(50, input_dim = features.shape[1], activation="relu"))
model.add(Dense(25, activation="relu"))
model.add(Dense(3, activation="softmax"))
model.compile(optimizer="rmsprop", loss=keras.losses.categorical_crossentropy, metrics=["accuracy"])

In [10]:
from keras.utils import to_categorical
labels = to_categorical(labels)

In [11]:
labels

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.

In [12]:
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, random_state=3, shuffle=True)

In [13]:
model.fit(features_train, labels_train, epochs=100, batch_size=25, validation_data=(features_test, labels_test))

Train on 112 samples, validate on 38 samples
Epoch 1/100
112/112 [==============================] - 0s 2ms/step - loss: 0.9362 - acc: 0.4911 - val_loss: 0.8552 - val_acc: 0.6842
Epoch 2/100
112/112 [==============================] - 0s 141us/step - loss: 0.8390 - acc: 0.6607 - val_loss: 0.7970 - val_acc: 0.6842
Epoch 3/100
112/112 [==============================] - 0s 138us/step - loss: 0.7944 - acc: 0.6607 - val_loss: 0.7632 - val_acc: 0.6842
Epoch 4/100
112/112 [==============================] - 0s 159us/step - loss: 0.7586 - acc: 0.6607 - val_loss: 0.7368 - val_acc: 0.6579
Epoch 5/100
112/112 [==============================] - 0s 208us/step - loss: 0.7243 - acc: 0.6607 - val_loss: 0.6774 - val_acc: 0.6842
Epoch 6/100
112/112 [==============================] - 0s 159us/step - loss: 0.6957 - acc: 0.6696 - val_loss: 0.6495 - val_acc: 0.6842
Epoch 7/100
112/112 [==============================] - 0s 172us/step - loss: 0.6641 - acc: 0.6607 - val_loss: 0.6272 - val_acc: 0.7105
Epoch 8/100


Epoch 61/100
112/112 [==============================] - 0s 125us/step - loss: 0.1644 - acc: 0.9643 - val_loss: 0.1385 - val_acc: 0.9737
Epoch 62/100
112/112 [==============================] - 0s 192us/step - loss: 0.1558 - acc: 0.9821 - val_loss: 0.1462 - val_acc: 0.9737
Epoch 63/100
112/112 [==============================] - 0s 157us/step - loss: 0.1568 - acc: 0.9732 - val_loss: 0.1605 - val_acc: 0.9474
Epoch 64/100
112/112 [==============================] - 0s 192us/step - loss: 0.1528 - acc: 0.9643 - val_loss: 0.1323 - val_acc: 0.9474
Epoch 65/100
112/112 [==============================] - 0s 172us/step - loss: 0.1451 - acc: 0.9821 - val_loss: 0.1865 - val_acc: 0.9211
Epoch 66/100
112/112 [==============================] - 0s 158us/step - loss: 0.1544 - acc: 0.9732 - val_loss: 0.1290 - val_acc: 0.9474
Epoch 67/100
112/112 [==============================] - 0s 180us/step - loss: 0.1513 - acc: 0.9643 - val_loss: 0.1202 - val_acc: 0.9737
Epoch 68/100
112/112 [==========================

In [14]:
pred = model.predict(features_test)

In [17]:
pred = np.round(pred)

In [18]:
model.predict_classes(features_test)

array([0, 0, 0, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 2, 0, 2, 2, 2, 0, 2, 2, 2,
       1, 0, 2, 2, 1, 1, 1, 0, 0, 2, 1, 0, 0, 1, 0])

In [19]:
labels_test

array([[ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.]])

In [24]:
np.argmax(labels_test, axis=1)

array([0, 0, 0, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 2, 0, 1, 2, 2, 0, 2, 2, 2,
       1, 0, 2, 2, 1, 1, 1, 0, 0, 2, 1, 0, 0, 1, 0])

In [25]:
features[0]

array([ 5.1,  3.5,  1.4,  0.2])

In [ ]:
features