In [38]:
import torch
from torch import autograd
from torch import nn
from torch.autograd import Variable

In [14]:
x = Variable(torch.Tensor([0]), requires_grad=True)

In [15]:
x.shape

torch.Size([1])

In [16]:
x

tensor([ 0.])

In [17]:
c = torch.sin(x)

In [18]:
c.backward()

In [19]:
c

tensor([ 0.])

In [20]:
x.grad

tensor([ 1.])

In [43]:
x = Variable(torch.Tensor([3]), requires_grad=True)
y = x ** 2

In [44]:
y

tensor([ 9.])

In [45]:
y.backward()

In [46]:
x.grad # x^2 => 2x

tensor([ 6.])