In [1]:
import torch

In [2]:
torch.__version__

'0.4.0'

In [27]:
x = torch.ones(2,2, requires_grad=True)

In [28]:
x

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [29]:
y = x * 2

In [30]:
y

tensor([[ 2.,  2.],
        [ 2.,  2.]])

In [31]:
y.grad_fn

In [32]:
y = y + 12 * 10

In [12]:
y

tensor([[ 122.,  122.],
        [ 122.,  122.]])

In [33]:
z = y.mean()

In [14]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [15]:
y

tensor([[ 122.,  122.],
        [ 122.,  122.]])

In [17]:
y

tensor([[ 122.,  122.],
        [ 122.,  122.]])

In [19]:
y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [23]:
y = torch.ones(1, requires_grad=True)

In [24]:
y

tensor([ 1.])

In [25]:
y.backward()

In [26]:
y.grad

tensor([ 1.])

In [34]:
z

tensor(122.)

In [35]:
z.backward()

In [37]:
z.grad

In [38]:
z

tensor(122.)

In [41]:
x = torch.ones(2,2, requires_grad=True)

In [42]:
x

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [43]:
y = x*x + 2

In [44]:
y

tensor([[ 3.,  3.],
        [ 3.,  3.]])

In [45]:
y.grad_fn

In [48]:
output = y.mean()

In [49]:
output

tensor(3.)

In [50]:
output.backward()

In [54]:
y

tensor([[ 3.,  3.],
        [ 3.,  3.]])

In [56]:
y.grad_fn

In [57]:
x.grad

tensor([[ 0.5000,  0.5000],
        [ 0.5000,  0.5000]])

In [58]:
output

tensor(3.)

In [59]:
x

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [60]:
x.grad

tensor([[ 0.5000,  0.5000],
        [ 0.5000,  0.5000]])

In [61]:
batch_size=64
input_dim = 1000
H = 100
output = 10

In [106]:
x = torch.randn(batch_size, input_dim)
y = torch.randn(batch_size, output)

In [65]:
x.shape

torch.Size([64, 1000])

In [66]:
y.shape

torch.Size([64, 10])

In [95]:
model = torch.nn.Sequential( 
    torch.nn.Linear(input_dim, H),
    torch.nn.ReLU(),
    torch.nn.Linear(H, output)
)

In [70]:
model

Sequential(
  (0): Linear(in_features=1000, out_features=100, bias=True)
  (1): ReLU()
  (2): Linear(in_features=100, out_features=10, bias=True)
)

In [71]:
loss_fn = torch.nn.MSELoss(size_average=False)

In [72]:
loss_fn

MSELoss()

In [73]:
lr = 0.00001

In [84]:
optimizer = torch.optim.Adam(model.parameters(),lr=lr)
for t in range(500):
    y_pred = model(x)
    
    loss = loss_fn(y_pred, y)
    
    optimizer.zero_grad()
    
    print (t, loss.item())
    loss.backward()
    optimizer.step()

0 2.5510780811309814
1 2.497006893157959
2 2.4442248344421387
3 2.3924505710601807
4 2.3415372371673584
5 2.2913715839385986
6 2.241933822631836
7 2.193284273147583
8 2.145406723022461
9 2.0983524322509766
10 2.052091598510742
11 2.006612777709961
12 1.9619697332382202
13 1.918089509010315
14 1.8750063180923462
15 1.8327534198760986
16 1.7911783456802368
17 1.7504388093948364
18 1.7104668617248535
19 1.671191692352295
20 1.6326886415481567
21 1.5948905944824219
22 1.557816505432129
23 1.5213748216629028
24 1.4857076406478882
25 1.4506853818893433
26 1.4163668155670166
27 1.3826943635940552
28 1.3497059345245361
29 1.3173702955245972
30 1.2856372594833374
31 1.2545489072799683
32 1.2241400480270386
33 1.1943297386169434
34 1.165114402770996
35 1.1364916563034058
36 1.1084734201431274
37 1.0810191631317139
38 1.0541400909423828
39 1.0278358459472656
40 1.0020848512649536
41 0.976894199848175
42 0.9522259831428528
43 0.9280776977539062
44 0.9044792652130127
45 0.8814493417739868
46 0.8588

391 2.4727482283992686e-08
392 2.2731082793825408e-08
393 2.0944455059179745e-08
394 1.922098213924528e-08
395 1.7689401943243865e-08
396 1.6212791109637692e-08
397 1.4903672962418568e-08
398 1.3702515566649254e-08
399 1.2617770828171615e-08
400 1.1560394419518616e-08
401 1.0624614077414662e-08
402 9.769951958560341e-09
403 8.980872046038257e-09
404 8.247962313134849e-09
405 7.583072836325755e-09
406 6.942618036021031e-09
407 6.3949205930668995e-09
408 5.8843721006951455e-09
409 5.392840840556801e-09
410 4.9669184321032844e-09
411 4.565849920368237e-09
412 4.201774039813699e-09
413 3.866412967568067e-09
414 3.557236727402824e-09
415 3.2876954492166988e-09
416 3.0380931104190267e-09
417 2.8018822817443834e-09
418 2.592659198441538e-09
419 2.385773134605529e-09
420 2.1832242680375202e-09
421 2.036546709049958e-09
422 1.8746386665213777e-09
423 1.7367796090184129e-09
424 1.6172345684850598e-09
425 1.4999566033679912e-09
426 1.382354453127732e-09
427 1.2984811004201902e-09
428 1.2011904804

In [87]:
model(x)

tensor([[ 0.2044,  0.0993, -0.2014,  0.1418,  0.4761, -0.3334, -0.5975,
          0.1119,  0.1036,  1.6189],
        [-0.0395, -0.1770, -0.3403, -0.3870,  1.3188,  0.7843, -1.8573,
         -0.3582, -2.1852,  1.4687],
        [ 0.2395,  2.1440,  0.7256, -0.3925, -0.4425, -0.2446,  0.5864,
          0.0175,  0.4021,  0.5384],
        [ 1.6520,  1.8150, -0.5895,  0.4817, -0.4521,  1.3234, -1.5491,
         -0.1496,  0.6170,  1.6410],
        [ 0.8639, -1.0313,  1.3064, -0.6706,  1.0874,  0.4264,  0.5151,
          0.8027,  0.4105, -1.1921],
        [-2.1385,  0.1517,  1.6480, -0.4272, -0.9012,  2.0525, -1.0993,
          1.0511, -0.5071,  1.1091],
        [-1.9430, -1.4017,  0.7424, -0.3892, -0.3394, -0.2491,  2.2769,
          0.3689, -1.2169, -0.6053],
        [ 0.6586, -1.3983,  0.3691,  1.3329,  0.1632,  0.7760,  0.5142,
         -0.1493,  0.0359,  0.5288],
        [-0.2754, -1.1055, -1.4322, -1.1166,  1.8896, -0.0907,  0.2977,
         -1.4087, -0.3779, -0.7132],
        [-0.7606,  

In [88]:
x

tensor([[-1.3026e-01,  4.1061e-01,  1.3140e+00,  ..., -1.8070e-01,
         -1.6921e+00, -3.3212e-01],
        [ 1.8450e-01, -1.0013e+00,  7.1709e-01,  ..., -2.8718e-01,
         -2.3109e-01, -1.3662e+00],
        [-1.1361e+00, -6.5719e-01, -8.7136e-01,  ..., -1.3898e+00,
         -5.8069e-01, -5.3959e-02],
        ...,
        [-3.3729e-01, -1.0465e+00,  3.4647e-01,  ...,  6.0241e-01,
          7.3158e-01,  8.4829e-01],
        [-4.0678e-01,  1.4929e+00,  1.0016e+00,  ..., -2.6611e-01,
          8.1009e-02, -3.5511e-01],
        [-8.1996e-01,  1.2899e+00, -3.4087e-01,  ..., -1.3661e+00,
          6.9666e-01,  5.6599e-01]])

In [89]:
x.shape

torch.Size([64, 1000])

In [99]:
x = model.parameters()

In [101]:
class NN(torch.nn.Module):
    def __init__(self, input_dim, h, output_dim):
        super(NN,self).__init__()
        self.linear1 = torch.nn.Linear(input_dim, h)
        self.linear2 = torch.nn.Linear(h, output_dim)
    
    def forward(self, x):
        h_relu = self.linear1(x).clamp(min=0)
        output = self.linear2(h_relu)
        return output

In [104]:
d = NN(input_dim, H, output)

In [112]:
for t in range(100):
    y_ = d(x)
    loss_fn = torch.nn.MSELoss()
    optimizer.zero_grad()  # Gradient = 0
    loss = loss_fn(y_, y)
    print (loss.item())
    loss.backward() # Backprop
    optimizer.step() # Updating weights

1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.056598424911499
1.05659842

In [111]:
optimizer

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 1e-05
    weight_decay: 0
)

In [113]:
optimizer.step()

In [114]:
optimizer

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 1e-05
    weight_decay: 0
)

In [115]:
d

NN(
  (linear1): Linear(in_features=1000, out_features=100, bias=True)
  (linear2): Linear(in_features=100, out_features=10, bias=True)
)

In [149]:
linear = torch.nn.Linear(100, 100)

In [150]:
x = torch.randn(64,100)

In [151]:
linear(x)

tensor([[-8.2263e-01,  7.0465e-01,  3.8445e-01,  ...,  1.1973e+00,
         -1.5793e+00,  5.7533e-01],
        [-5.7792e-01,  2.9865e-01,  4.5245e-01,  ..., -1.0411e-01,
         -5.0436e-01,  6.3357e-01],
        [ 3.7090e-01, -4.1821e-01,  7.0710e-01,  ...,  3.8338e-01,
          1.6227e-01,  2.8721e-01],
        ...,
        [-1.0006e+00, -3.7468e-02,  9.7670e-01,  ..., -1.0902e+00,
          4.3084e-01, -5.4180e-02],
        [-4.7938e-01,  5.4371e-01, -4.9878e-02,  ..., -7.4853e-01,
         -7.5786e-01,  1.5172e-01],
        [ 9.4257e-01,  1.0826e+00, -6.7559e-01,  ..., -1.0472e+00,
         -1.2825e-01, -6.2468e-01]])

In [153]:
y.shape

torch.Size([64, 10])

In [157]:
c = torch.nn.ReLU()
c = torch.nn.Sigmoid()

In [158]:
c(torch.ones(10,10))

tensor([[ 0.7311,  0.7311,  0.7311,  0.7311,  0.7311,  0.7311,  0.7311,
          0.7311,  0.7311,  0.7311],
        [ 0.7311,  0.7311,  0.7311,  0.7311,  0.7311,  0.7311,  0.7311,
          0.7311,  0.7311,  0.7311],
        [ 0.7311,  0.7311,  0.7311,  0.7311,  0.7311,  0.7311,  0.7311,
          0.7311,  0.7311,  0.7311],
        [ 0.7311,  0.7311,  0.7311,  0.7311,  0.7311,  0.7311,  0.7311,
          0.7311,  0.7311,  0.7311],
        [ 0.7311,  0.7311,  0.7311,  0.7311,  0.7311,  0.7311,  0.7311,
          0.7311,  0.7311,  0.7311],
        [ 0.7311,  0.7311,  0.7311,  0.7311,  0.7311,  0.7311,  0.7311,
          0.7311,  0.7311,  0.7311],
        [ 0.7311,  0.7311,  0.7311,  0.7311,  0.7311,  0.7311,  0.7311,
          0.7311,  0.7311,  0.7311],
        [ 0.7311,  0.7311,  0.7311,  0.7311,  0.7311,  0.7311,  0.7311,
          0.7311,  0.7311,  0.7311],
        [ 0.7311,  0.7311,  0.7311,  0.7311,  0.7311,  0.7311,  0.7311,
          0.7311,  0.7311,  0.7311],
        [ 0.7311,  

In [159]:
torch.ones(10,10)

tensor([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [160]:
from sklearn.datasets import make_classification

In [161]:
data = make_classification(n_features=5)

In [162]:
features = data[0]
labels = data[1]

In [163]:
features.shape

(100, 5)

In [230]:
model = torch.nn.Sequential(
    torch.nn.Linear(features.shape[1],100),
    torch.nn.ReLU(),
    torch.nn.Linear(100,74),
    torch.nn.ReLU(),
    torch.nn.Linear(74, 2),
    torch.nn.Softmax()
)

In [231]:
model

Sequential(
  (0): Linear(in_features=5, out_features=100, bias=True)
  (1): ReLU()
  (2): Linear(in_features=100, out_features=74, bias=True)
  (3): ReLU()
  (4): Linear(in_features=74, out_features=2, bias=True)
  (5): Softmax()
)

In [232]:
pred = model(torch.from_numpy(features).float())

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/nn/modules/container.py:91: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)


In [187]:
import numpy as np

In [197]:
pred = pred.detach().numpy()

In [198]:
np.argmax(pred, axis=1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [199]:
labels

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0])

In [205]:
optimizer = torch.optim.Adam(model.parameters(),lr=0.001)

In [210]:
for t in range(1000):
    y_ = model(torch.from_numpy(features).float())
    loss_fn = torch.nn.CrossEntropyLoss()
    loss = loss_fn(y_, torch.from_numpy(labels).long())
    print (t, loss.item())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/nn/modules/container.py:91: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)


0 0.34348297119140625
1 0.3434823155403137
2 0.3434818685054779
3 0.34348130226135254
4 0.34348064661026
5 0.34348008036613464
6 0.3434794247150421
7 0.3434787094593048
8 0.3434782028198242
9 0.34347766637802124
10 0.3434771001338959
11 0.34347644448280334
12 0.34347590804100037
13 0.34347546100616455
14 0.343474805355072
15 0.34347423911094666
16 0.34347379207611084
17 0.34347325563430786
18 0.34347274899482727
19 0.34347209334373474
20 0.34347155690193176
21 0.3434709906578064
22 0.3434704840183258
23 0.3434700071811676
24 0.34346938133239746
25 0.34346893429756165
26 0.34346842765808105
27 0.3434678912162781
28 0.3434674143791199
29 0.3434669077396393
30 0.3434663414955139
31 0.3434658348560333
32 0.3434653878211975
33 0.34346482157707214
34 0.34346428513526917
35 0.3434637188911438
36 0.3434630334377289
37 0.34346267580986023
38 0.3434622287750244
39 0.3434616029262543
40 0.34346118569374084
41 0.3434606194496155
42 0.3434600830078125
43 0.3434596359729767
44 0.34345921874046326
45

368 0.34335997700691223
369 0.3433598279953003
370 0.34335964918136597
371 0.34335950016975403
372 0.3433593511581421
373 0.3433590829372406
374 0.3433590233325958
375 0.34335875511169434
376 0.3433585464954376
377 0.3433583378791809
378 0.34335818886756897
379 0.34335801005363464
380 0.34335780143737793
381 0.343357652425766
382 0.34335747361183167
383 0.3433573544025421
384 0.3433571755886078
385 0.3433569669723511
386 0.343356728553772
387 0.3433566689491272
388 0.34335651993751526
389 0.34335631132125854
390 0.34335610270500183
391 0.3433559536933899
392 0.34335583448410034
393 0.34335562586784363
394 0.3433554172515869
395 0.343355268239975
396 0.34335505962371826
397 0.34335488080978394
398 0.343354731798172
399 0.34335458278656006
400 0.34335437417030334
401 0.3433542251586914
402 0.34335407614707947
403 0.34335392713546753
404 0.3433537185192108
405 0.3433535695075989
406 0.34335342049598694
407 0.34335318207740784
408 0.3433530330657959
409 0.34335291385650635
410 0.3433527350

738 0.3433153033256531
739 0.3433152437210083
740 0.34331515431404114
741 0.34331509470939636
742 0.3433149755001068
743 0.3433149456977844
744 0.34331485629081726
745 0.3433147668838501
746 0.3433147072792053
747 0.34331461787223816
748 0.3433145582675934
749 0.3433144688606262
750 0.34331440925598145
751 0.3433143198490143
752 0.3433142602443695
753 0.34331417083740234
754 0.3433140814304352
755 0.3433140218257904
756 0.343313992023468
757 0.34331387281417847
758 0.3433137834072113
759 0.34331372380256653
760 0.34331363439559937
761 0.3433135747909546
762 0.34331345558166504
763 0.34331339597702026
764 0.3433133363723755
765 0.3433133065700531
766 0.34331321716308594
767 0.343313068151474
768 0.3433130383491516
769 0.34331294894218445
770 0.3433128595352173
771 0.3433127999305725
772 0.34331271052360535
773 0.34331268072128296
774 0.3433126211166382
775 0.343312531709671
776 0.34331244230270386
777 0.3433123826980591
778 0.3433122932910919
779 0.34331226348876953
780 0.34331217408180

In [211]:
p = model(torch.from_numpy(features).float())

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/torch/nn/modules/container.py:91: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)


In [218]:
c = np.argmax(p.detach().numpy(), axis=1)

In [217]:
labels

array([1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0])

In [219]:
from sklearn.metrics import accuracy_score

In [220]:
accuracy_score(labels, c)

0.97