# <u>Support Vector Machines</u>

In [6]:
from sklearn.svm import SVC
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import keras
from keras.layers import Dense
from keras import Sequential
import numpy as np
from keras.utils import to_categorical

Using TensorFlow backend.


In [7]:
features,labels = load_iris(return_X_y=True)

In [8]:
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, random_state=34)

In [21]:
clf = SVC(kernel="rbf",probability=True)
clf.fit(features_train, labels_train)
print ("Testing: ", clf.score(features_test, labels_test))
print ("Training: ", clf.score(features_train, labels_train))

Testing:  1.0
Training:  0.973214285714


In [37]:
# Testing with a nn, if we increase the number of layers or the number of units no considerable amount of change is observed.
model = Sequential()
model.add(Dense(25, activation="relu", input_dim=features_train.shape[1]))
model.add(Dense(72, activation="relu"))
model.add(Dense(3, activation="softmax"))

model.compile(optimizer="adam", loss=keras.losses.categorical_crossentropy, metrics=["acc"])

In [23]:
labels_train = to_categorical(labels_train)

In [24]:
labels_test = to_categorical(labels_test)

In [26]:
model.fit(features_train, labels_train, epochs=100)

Epoch 1/100
112/112 [==============================] - 0s 126us/step - loss: 0.5673 - acc: 0.7232
Epoch 2/100
112/112 [==============================] - 0s 88us/step - loss: 0.5492 - acc: 0.7500
Epoch 3/100
112/112 [==============================] - 0s 93us/step - loss: 0.5309 - acc: 0.8304
Epoch 4/100
112/112 [==============================] - 0s 102us/step - loss: 0.5111 - acc: 0.8304
Epoch 5/100
112/112 [==============================] - 0s 114us/step - loss: 0.4933 - acc: 0.7946
Epoch 6/100
112/112 [==============================] - 0s 117us/step - loss: 0.4786 - acc: 0.7946
Epoch 7/100
112/112 [==============================] - 0s 127us/step - loss: 0.4668 - acc: 0.7679
Epoch 8/100
112/112 [==============================] - 0s 116us/step - loss: 0.4506 - acc: 0.8304
Epoch 9/100
112/112 [==============================] - 0s 82us/step - loss: 0.4385 - acc: 0.8482
Epoch 10/100
112/112 [==============================] - 0s 99us/step - loss: 0.4280 - acc: 0.8929
Epoch 11/100
112/112 [=

In [27]:
pred = model.predict(features_test)

In [29]:
pred = np.argmax(pred, axis=1)

In [30]:
pred

array([1, 2, 0, 1, 2, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 2, 0, 1, 1,
       2, 0, 1, 1, 0, 1, 1, 2, 0, 0, 1, 0, 0, 1, 0])

In [31]:
labels_test = np.argmax(labels_test, axis=1)

In [32]:
from sklearn.metrics import accuracy_score
accuracy_score(labels_test, pred)

1.0

In [34]:
labels_test = to_categorical(labels_test)
model.evaluate(features_test, labels_test)

38/38 [==============================] - 0s 983us/step


[0.05862190956740003, 1.0]

In [36]:
 np.where(pred!=np.argmax(labels_test, axis=1)) # No misclassified point

(array([], dtype=int64),)

In [47]:
from sklearn.datasets import make_circles

In [61]:
data = make_circles(n_samples=50000,noise=1)

In [74]:
len(data[1])
len(data[0])

features, labels = data[0], data[1]
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, random_state=34, shuffle=True)


In [67]:
# Experimentation
k = Sequential()
k.add(Dense(100, activation="relu", input_dim=features.shape[1]))
k.add(Dense(100, activation="relu"))
k.add(Dense(100, activation="relu"))
k.add(Dense(1, activation="sigmoid"))
k.compile(optimizer="adam", loss=keras.losses.binary_crossentropy, metrics=['acc'])

In [68]:
k.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_11 (Dense)             (None, 100)               300       
_________________________________________________________________
dense_12 (Dense)             (None, 100)               10100     
_________________________________________________________________
dense_13 (Dense)             (None, 100)               10100     
_________________________________________________________________
dense_14 (Dense)             (None, 1)                 101       
Total params: 20,601
Trainable params: 20,601
Non-trainable params: 0
_________________________________________________________________


In [75]:
k.fit(features_train, labels_train, epochs=100)

Epoch 1/100
37500/37500 [==============================] - 3s 79us/step - loss: 0.6921 - acc: 0.5193
Epoch 2/100
37500/37500 [==============================] - 2s 63us/step - loss: 0.6915 - acc: 0.5256
Epoch 3/100
37500/37500 [==============================] - 2s 62us/step - loss: 0.6912 - acc: 0.5271
Epoch 4/100
37500/37500 [==============================] - 2s 62us/step - loss: 0.6912 - acc: 0.5275
Epoch 5/100
37500/37500 [==============================] - 2s 63us/step - loss: 0.6910 - acc: 0.5297
Epoch 6/100
37500/37500 [==============================] - 2s 62us/step - loss: 0.6910 - acc: 0.5281
Epoch 7/100
37500/37500 [==============================] - 2s 63us/step - loss: 0.6910 - acc: 0.5274
Epoch 8/100
37500/37500 [==============================] - 2s 63us/step - loss: 0.6909 - acc: 0.5290: 0s - loss: 0.6909 -
Epoch 9/100
37500/37500 [==============================] - 2s 66us/step - loss: 0.6908 - acc: 0.5296
Epoch 10/100
37500/37500 [==============================] - 3s 70us/st

KeyboardInterrupt: 

In [70]:
labels_train

array([[-1.34972792, -1.57921755],
       [-0.23643763,  0.38566625],
       [-0.65857801, -0.99498635],
       ..., 
       [ 0.29659331, -1.64319431],
       [-0.98824319,  1.20133493],
       [-1.02891853,  1.63337717]])

In [71]:
features

array([[ 0.47361779, -0.2658943 ],
       [-0.43042046,  0.12051038],
       [-1.0933412 , -1.57985635],
       ..., 
       [ 1.15149605, -1.50401462],
       [ 1.82553073, -1.01452914],
       [ 3.10851979, -1.44037792]])

In [73]:
labels_train

array([[-1.34972792, -1.57921755],
       [-0.23643763,  0.38566625],
       [-0.65857801, -0.99498635],
       ..., 
       [ 0.29659331, -1.64319431],
       [-0.98824319,  1.20133493],
       [-1.02891853,  1.63337717]])

In [2]:
# C is a regularization.
# We need to choose a middle value of C

In [4]:
# SVM objective is to maximize the margin.
# The margin is defined as the distance between the separating decision boundary and the training samples that are closest to the hyperplance which are called support vectors.

In [10]:
clf

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [19]:
clf.decision_function(features) # Used to find distance of the data point from decision boundary

array([[ 2.40106928, -0.20836932,  0.80730004],
       [ 2.3880326 , -0.19771186,  0.80967927],
       [ 2.39666854, -0.21830903,  0.82164049],
       [ 2.37644346, -0.19487104,  0.81842758],
       [ 2.40076876, -0.21306488,  0.81229612],
       [ 2.3642535 ,  0.84146058, -0.20571408],
       [ 2.38542461, -0.20988417,  0.82445957],
       [ 2.39400596,  0.80269871, -0.19670468],
       [ 2.36585265, -0.19949048,  0.83363783],
       [ 2.38424031,  0.80707165, -0.19131196],
       [ 2.38591954,  0.81047863, -0.19639817],
       [ 2.38071671,  0.81130315, -0.19201986],
       [ 2.3874413 , -0.20367587,  0.81623457],
       [ 2.3670745 , -0.22211227,  0.85503777],
       [ 2.35292313, -0.19247054,  0.83954741],
       [ 2.3396232 , -0.17270891,  0.8330857 ],
       [ 2.38702925, -0.20372883,  0.81669958],
       [ 2.40017696,  0.79537627, -0.19555323],
       [ 2.34664481,  0.85684755, -0.20349236],
       [ 2.39168928,  0.80033838, -0.19202766],
       [ 2.35824746,  0.85254345, -0.210

In [13]:
features[0]

array([ 5.1,  3.5,  1.4,  0.2])

In [24]:
np.argmax(clf.predict_proba(features), axis=1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [25]:
from sklearn.linear_model import LogisticRegression

In [26]:
lg = LogisticRegression()

In [28]:
lg.fit(features, labels)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [29]:
lg.score(features, labels)

0.95999999999999996